# Site settings
title:          Hill Zhang
description:    "Minimal Jekyll theme for storytellers"
baseurl:        ""
url:            "https://hillzhang.github.io"

# Author
author:
  name:         Hill Zhang
  url:          https://hillzhang.github.io
  email:        hillzhang1992@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
